import Head from "next/head";

// import { api } from "~/utils/api";

export default function Home() {
  // keeping an example here of how to call tRPC
  // const postQuery = api.post.all.useQuery();
  /**
   * 
  const deletePostMutation = api.post.delete.useMutation({
    onSettled: () => postQuery.refetch(),
  });
   */

  return (
    <>
      <Head>
        <title>Igloo NextJS App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <h1 className="text-5xl font-extrabold">
          This is the NextJS site... <span className="text-red-500">wow!</span>
        </h1>
      </main>
    </>
  );
}
